# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "NOC Helpdesk",
    "summary": "Core NOC helpdesk configuration",
    "version": "16.0.0.7.0",
    "post_init_hook": "post_init_hook",
    "license": "AGPL-3",
    "author": "Tanatielly Serafim",
    "website": "https://github.com/OCA/helpdesk",
    "depends": [
        "helpdesk_mgmt",
        "noc_helpdesk_inventory",
        "web",
        "document_page",
        "document_page_access_group",
        "noc_contacts",
    ],
    "data": [
        "security/security.xml",
        "data/helpdesk_category.xml",
        "data/helpdesk_ticket_tags.xml",
        "data/helpdesk_doc_categories.xml",
        "data/helpdesk_stage_id.xml",
        "data/helpdesk_teams.xml",
        "data/ir_cron.xml",
        "data/server_actions.xml",
        "views/helpdesk_escala_views.xml",
        "views/helpdesk_ferias_views.xml",
        "data/mail_activity_type.xml",
        "security/ir.model.access.csv",
        "reports/helpdesk_ticket_report.xml",
        "views/helpdesk_menu_hide_view.xml",
        "views/helpdesk_menu_actions.xml",
        "views/helpdesk_main_menu_view.xml",
        "views/helpdesk_ticket_list_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/res_partner_view.xml",
        "views/helpdesk_ticket_inventory_decorations.xml",
        "views/portal_ticket_templates.xml",
        "views/mail_activity.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "noc_helpdesk/static/src/xml/helpdesk_extra_menu.xml",
            "noc_helpdesk/static/src/js/helpdesk_extra_menu.js",
            "noc_helpdesk/static/src/js/helpdesk_alerts.js",
            "noc_helpdesk/static/src/js/helpdesk_live_updates.js",
            "noc_helpdesk/static/src/scss/helpdesk_ticket_style.scss",
        ],
        "mail.assets_messaging": [
            "noc_helpdesk/static/src/js/chatter_patch.js",
            "noc_helpdesk/static/src/xml/chatter_patch.xml",
        ],
        "web.assets_frontend": [
            "noc_helpdesk/static/src/scss/portal_theme.scss",
            "noc_helpdesk/static/src/js/portal_ticket.js",
        ],
    },
    "application": True,
    "installable": True,
}
