{
    "name": "NOC Helpdesk Dashboard",
    "version": "16.0.0.1.0",
    "summary": "Network fault monitoring dashboard and monthly reports",
    "category": "Helpdesk",
    "author": "Tanatielly Serafim",
    "depends": [
        "base",
        "web",
        "helpdesk_mgmt",
        "noc_helpdesk",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/activity_occupancy_views.xml",
        "views/monthly_report_views.xml",
        "views/dashboard_menu.xml",
        "data/activity_category_data.xml",
        "reports/monthly_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "noc_helpdesk_dashboard/static/lib/chart.umd.min.js",
            "noc_helpdesk_dashboard/static/src/css/dashboard.css",
            "noc_helpdesk_dashboard/static/src/js/dashboard.js",
            "noc_helpdesk_dashboard/static/src/xml/dashboard.xml",
            "noc_helpdesk_dashboard/static/src/js/activity_occupancy.js",
            "noc_helpdesk_dashboard/static/src/xml/activity_occupancy.xml",
            "noc_helpdesk_dashboard/static/src/js/monthly_report.js",
            "noc_helpdesk_dashboard/static/src/xml/monthly_report.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": True,
    "license": "LGPL-3",
    "images": [],
}
